Allow setting Android NDK bin path via env var

diff --git a/Samples/Beyond.NET.Sample.Native/publish_android_arm64 b/Samples/Beyond.NET.Sample.Native/publish_android_arm64
--- a/Samples/Beyond.NET.Sample.Native/publish_android_arm64
+++ b/Samples/Beyond.NET.Sample.Native/publish_android_arm64
@@ -4,23 +4,26 @@
 
 set -e
 
-# Make sure the "ANDROID_NDK_HOME" enviroment variable is set and pointing to your Android NDK installation.
-if [ ! -d "${ANDROID_NDK_HOME}" ] ; then
-  echo "Error: ANDROID_NDK_HOME enviroment variable is not set or directory does not exist"
-  exit 1
-fi
-
-echo "Android NDK Home: ${ANDROID_NDK_HOME}"
-
-# ndk_bin_common.sh sets the "HOST_TAG" environment variable to the NDK's toolchain platform
-source "${ANDROID_NDK_HOME}/build/tools/ndk_bin_common.sh"
-echo "Android Host Tag: ${HOST_TAG}"
-
-ANDROID_NDK_BIN_PATH="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/${HOST_TAG}/bin"
-
+# Either set the "ANDROID_NDK_BIN_PATH" environment variable and point it to the following Android NDK installation directory's subpath "ndk_home/toolchains/llvm/prebuilt/platform-arch/bin"
+# Or alternatively, make sure the "ANDROID_NDK_HOME" enviroment variable is set and pointing to your Android NDK installation. We'll then try to automatically detect where the bin path is.
 if [ ! -d "${ANDROID_NDK_BIN_PATH}" ] ; then
-  echo "Error: Android NDK bin Path not found at ${ANDROID_NDK_BIN_PATH}"
-  exit 1
+  if [ ! -d "${ANDROID_NDK_HOME}" ] ; then
+    echo "Error: ANDROID_NDK_HOME enviroment variable is not set or directory does not exist"
+    exit 1
+  fi
+
+  echo "Android NDK Home: ${ANDROID_NDK_HOME}"
+
+  # ndk_bin_common.sh sets the "HOST_TAG" environment variable to the NDK's toolchain platform
+  source "${ANDROID_NDK_HOME}/build/tools/ndk_bin_common.sh"
+  echo "Android Host Tag: ${HOST_TAG}"
+
+  ANDROID_NDK_BIN_PATH="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/${HOST_TAG}/bin"
+
+  if [ ! -d "${ANDROID_NDK_BIN_PATH}" ] ; then
+    echo "Error: Android NDK bin Path not found at ${ANDROID_NDK_BIN_PATH}"
+    exit 1
+  fi
 fi
 
 echo "Android NDK bin Path: ${ANDROID_NDK_BIN_PATH}"
